"""Shared helpers for backend command generation."""

from __future__ import annotations

from ..config.models import HookConfig
from ..executor import CommandSpec


def split_hooks(
    hooks: HookConfig, prefix: str
) -> tuple[list[CommandSpec], list[CommandSpec]]:
    """Build command specs for pre- and post-hooks separately.

    Args:
        hooks: Hook configuration containing pre- and post-command arrays.
        prefix: Description prefix used for generated hook command specs.

    Returns:
        Pre-hook and post-hook command specs in execution order.
    """

    pre = [
        CommandSpec(command=command, description=f"{prefix} pre-hook")
        for command in hooks.pre
    ]
    post = [
        CommandSpec(command=command, description=f"{prefix} post-hook")
        for command in hooks.post
    ]
    return pre, post


def prepend_launcher(command: list[str], launcher: list[str]) -> list[str]:
    """Prepend an optional launcher command prefix.

    Args:
        command: Backend command generated by the adapter.
        launcher: Optional launcher command configured for the backend entry.

    Returns:
        Full command line with the launcher prefix prepended when configured.
    """

    if not launcher:
        return list(command)
    return [*launcher, *command]
