"""Shared constants for config parsing and CLI selection."""

DEFAULT_CONFIG_FILENAME = "foga.yml"
NATIVE_WORKFLOW_KIND = "native"
PYTHON_WORKFLOW_KIND = "python"
ALL_WORKFLOW_SELECTION = "all"

WORKFLOW_KINDS = (NATIVE_WORKFLOW_KIND, PYTHON_WORKFLOW_KIND)
WORKFLOW_SELECTIONS = (*WORKFLOW_KINDS, ALL_WORKFLOW_SELECTION)
