"""Shared constants for config parsing and CLI selection."""

DEFAULT_CONFIG_FILENAME = "foga.yml"
CPP_WORKFLOW_KIND = "cpp"
PYTHON_WORKFLOW_KIND = "python"
ALL_WORKFLOW_SELECTION = "all"

WORKFLOW_KINDS = (CPP_WORKFLOW_KIND, PYTHON_WORKFLOW_KIND)
WORKFLOW_SELECTIONS = (*WORKFLOW_KINDS, ALL_WORKFLOW_SELECTION)
